version: '3.9'

services:
  database_rent:
    image: postgres
    container_name: database_rent
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=shitsu
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - database_rent
    depends_on:
      - database_rent


volumes:
  pgdata:
    driver: local